version: '3'

services:
  db_postgres:
    container_name: 'db_boilerplate'
    image: 'postgres:12.6-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - 5432
    volumes:
      - ./database/boilerplate:/var/lib/postgresql/data/

  be_boilerplate:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db_postgres
    links:
      - db_postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db_postgres

  be_boilerplate_test:
    container_name: 'be_test_boilerplate'
    command: echo 'Test container ready'
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db_postgres
    links:
      - db_postgres
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
volumes:
    pgadmin-data:
